@startuml
' Definição da classe Character
class Character {
    int level
    int strength
    int xp
    int xpToNextLevel
    int currentHp
    int currentMp
    Map<String, String?> equipment
    List<String> inventory
    + totalStrength(): int
    + totalHp(): int
    + totalMp(): int
}

' Definição da classe Quest
class Quest {
    String name
    String description
    int rewardPoints
    int penaltyPoints
    bool isCompleted
    bool isCancelled
    int remainingTime
}

' Definição da classe Combat
class Combat {
    int opponentLevel
    int opponentStrength
    String reward
}

' Relações entre as classes
Character "1" -- "0..*" Quest : completes
Character "1" -- "0..*" Combat : participates in
@enduml
