name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_cloud_firestore: ^3.1.0
  fake_async: ^1.3.1
  firebase_auth_mocks: ^0.14.1  # Versão com suporte a null safety
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/images/character.png  # Adicione esta linha para o asset da imagem
    - assets/images/enemy.png
    - assets/images/logo.png
